name: mytax
channels:
  - conda-forge
  - bioconda
  - defaults
  - anaconda
  - r
dependencies:
  - gawk=5.1.0
  - kraken2=2.1.2
  - kmer-jellyfish=1.1.12
  - make=4.3
  - pandas=1.3.4
  - anytree=2.8.0
