name: mytax
channels:
  - conda-forge
  - anaconda
  - bioconda
  - r
  - defaults
dependencies:
  - blast=2.12.0
  - bzip2=1.0.8
  - gawk=5.1.0
  - c-ares=1.18.0
  - ca-certificates=2021.10.8
  - curl=7.79.1
  - entrez-direct=15.6
  - gettext=0.19.8.1
  - kmer-jellyfish=1.1.12
  - kraken=1.1.1
  - kraken2=2.1.2
  - krb5=1.19.2
  - libcurl=7.79.1
  - libcxx=12.0.1
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.4.2
  - libiconv=1.16
  - libidn2=2.3.2
  - libnghttp2=1.43.0
  - libssh2=1.10.0
  - libunistring=0.9.10
  - libzlib=1.2.11
  - llvm-openmp=12.0.1
  - lz4-c=1.9.3
  - ncurses=6.2
  - openssl=3.0.0
  - pcre=8.45
  - perl=5.26.2
  - perl-archive-tar=2.32
  - perl-carp=1.38
  - perl-common-sense=3.74
  - perl-compress-raw-bzip2=2.087
  - perl-compress-raw-zlib=2.087
  - perl-exporter=5.72
  - perl-exporter-tiny=1.002001
  - perl-extutils-makemaker=7.36
  - perl-io-compress=2.087
  - perl-io-zlib=1.10
  - perl-json=4.02
  - perl-json-xs=2.34
  - perl-list-moreutils=0.428
  - perl-list-moreutils-xs=0.428
  - perl-pathtools=3.75
  - perl-scalar-list-utils=1.52
  - perl-types-serialiser=1.0
  - perl-xsloader=0.24
  - pip=21.3.1
  - popt=1.16
  - python=3.8.12
  - python_abi=3.8
  - readline=8.1
  - rsync=3.2.3
  - setuptools=58.2.0
  - sqlite=3.36.0
  - tar=1.34
  - tk=8.6.11
  - wget=1.20.3
  - wheel=0.37.0
  - xxhash=0.8.0
  - xz=5.2.5
  - zlib=1.2.11
  - zstd=1.5.0
  - make
  - pip:
    - anytree==2.8.0
    - numpy==1.21.3
    - pandas==1.3.4
    - python-dateutil==2.8.2
    - pytz==2021.3
    - six==1.16.0
