name: Build and push Docker image for pre-release

on:
  push:
    branches: prerelease

jobs:
  push_to_registry:
    name: Build and push Docker image for pre-release
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          name: jhuaplbio/basestack_mytax
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: jhuaplbio/basestack_mytax
          tag_with_ref: true
          tag_with_sha: true
          tags: prerelease
          lfs: true
