name: Build and push Docker image upon release
on:
  push:
    branches:
      - build
jobs:
  push_to_registry:
    name: Build and push Docker image upon release
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.3.1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and Push to Docker Hub
        uses: docker/build-push-action@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          tag_with_ref: true
          tag_with_sha: true
          context: .
          push: true
          file: "./Dockerfile"
          platforms: linux/amd64,linux/arm64
          tags: jhuaplbio/basestack_mytax2:latest
